import os
import datetime
import uuid

# --- 1. KONFIGURÁCIÓ ÉS ADATSTRUKTÚRA ---

class ContentData:
    def __init__(self):
        self.timestamp = datetime.datetime.now().strftime("%Y-%m-%d")
        self.doc_id_base = datetime.datetime.now().strftime("%Y%m%d")
        self.version = "1.0.5-GOLD"
        self.author = "LemonScript LAB (Citrom Media LTD)"
        
        # TABLE DATA
        self.fmea_table_data = [
            ["FM-01", "GPS Spoofing", "10", "9 (Late/Unreliable)", "1 (Instant <100ms)", "+88.9%"],
            ["FM-02", "Solar Panel", "7", "10 (Blind/Undetected)", "1 (Instant <100ms)", "+90.0%"],
            ["FM-03", "Battery Fault", "9", "8 (Voltage only)", "1 (Power Balance)", "+87.5%"]
        ]
        
        self.fmea_table_headers = {
            'hu': ["ID", "Hiba Mód", "Súlyosság (S)", "EKF Észlelés (D)", "MetaSpace Észlelés (D)", "Javulás"],
            'ro': ["ID", "Mod Defectare", "Severitate (S)", "Detectare EKF (D)", "Detectare MetaSpace (D)", "Îmbunătățire"],
            'en': ["ID", "Failure Mode", "Severity (S)", "EKF Detection (D)", "MetaSpace Detection (D)", "Improvement"]
        }

        self.validation_table_data = [
            ["Unit Tests (Physics)", "3", "3", "0", "100%"],
            ["Integration (FDIR)", "2", "2", "0", "100%"],
            ["System (Full Sim)", "1", "1", "0", "100%"],
            ["Stress Test (Batch)", "100", "100", "0", "100%"]
        ]
        
        self.validation_table_headers = {
            'hu': ["Teszt Kategória", "Összes", "Sikeres", "Sikertelen", "Arány"],
            'ro': ["Categorie Test", "Total", "Reușit", "Eșuat", "Rată"],
            'en': ["Test Category", "Total", "Passed", "Failed", "Success Rate"]
        }

    def get_content(self, lang):
        def make_md_table(headers, rows):
            # Safe table generator using list joins
            lines = ["| " + " | ".join(headers) + " |"]
            lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
            for row in rows:
                lines.append("| " + " | ".join(row) + " |")
            return "\n".join(lines)

        t = {}
        # Metadata
        if lang == 'hu':
            t['meta'] = {'company': self.author, 'project': 'MetaSpace Műhold Szimuláció', 'doc_id_label': 'DOK-AZ', 'date_label': 'Dátum', 'ver_label': 'Verzió', 'auth_label': 'Szerző', 'status': 'CONFIDENTIAL', 'sheet_label': 'Lap', 'footer': 'Generálta a MetaSpace Tanúsítási Motor.'}
        elif lang == 'ro':
            t['meta'] = {'company': self.author, 'project': 'Simulare Satelit MetaSpace', 'doc_id_label': 'ID-DOC', 'date_label': 'Data', 'ver_label': 'Versiune', 'auth_label': 'Autor', 'status': 'CONFIDENTIAL', 'sheet_label': 'Foaie', 'footer': 'Generat de Motorul de Certificare MetaSpace.'}
        else: # EN
            t['meta'] = {'company': self.author, 'project': 'MetaSpace Satellite Simulation', 'doc_id_label': 'DOC-ID', 'date_label': 'Date', 'ver_label': 'Version', 'auth_label': 'Author', 'status': 'CONFIDENTIAL', 'sheet_label': 'Sheet', 'footer': 'Generated by MetaSpace Certification Engine.'}

        # --- CONTENT ---
        if lang == 'hu':
            t['safety'] = {'title': 'Biztonsági Esettanulmány', 'sections': [('1. Összefoglaló', 'A MetaSpace SIL 3 biztonsági szintet garantál.'), ('2. Veszélyelemzés', 'GPS hiba, akku lemerülés elleni védelem.'), ('3. Következtetés', 'A rendszer biztonságos és készen áll a repülésre.')]}
            t['spec'] = {'title': 'Rendszerspecifikáció', 'sections': [('1. Fizika', 'Landsat-9 dinamikai modell.'), ('2. Interfész', 'Bemenetek: GPS, IMU, EPS.')]}
            t['fmea'] = {'title': 'FMEA Jelentés', 'sections': [('1. Metodológia', 'RPN = S * O * D'), ('2. FMEA Mátrix', make_md_table(self.fmea_table_headers[lang], self.fmea_table_data))]}
            t['valid'] = {'title': 'Validációs Jelentés', 'sections': [('1. Környezet', 'MetaSpace Core v2.0 Sandbox'), ('2. Tesztesetek', 'TC-01..TC-04 Stress Test'), ('3. Eredmények', make_md_table(self.validation_table_headers[lang], self.validation_table_data)), ('4. Ítélet', 'RENDSZER ELFOGADVA.')]}
        elif lang == 'ro':
            t['safety'] = {'title': 'Caz de Siguranță', 'sections': [('1. Rezumat', 'Sistemul MetaSpace este conform SIL 3.'), ('2. Analiză', 'Protecție GPS și Baterie.'), ('3. Concluzie', 'Sistemul este sigur pentru zbor.')]}
            t['spec'] = {'title': 'Specificația Sistemului', 'sections': [('1. Fizică', 'Model dinamic Landsat-9.'), ('2. Interfață', 'Intrări: GPS, IMU, EPS.')]}
            t['fmea'] = {'title': 'Raport FMEA', 'sections': [('1. Metodologie', 'RPN = S * O * D'), ('2. Matrice FMEA', make_md_table(self.fmea_table_headers[lang], self.fmea_table_data))]}
            t['valid'] = {'title': 'Raport de Validare', 'sections': [('1. Mediu', 'MetaSpace Core v2.0 Sandbox'), ('2. Cazuri', 'TC-01..TC-04 Stress Test'), ('3. Rezultate', make_md_table(self.validation_table_headers[lang], self.validation_table_data)), ('4. Verdict', 'SISTEM ACCEPTAT.')]}
        else: # EN
            t['safety'] = {'title': 'Safety Case', 'sections': [('1. Abstract', 'MetaSpace guarantees SIL 3 safety.'), ('2. Hazards', 'GPS and Battery failure protection.'), ('3. Conclusion', 'System is safe for flight.')]}
            t['spec'] = {'title': 'System Spec', 'sections': [('1. Physics', 'Landsat-9 dynamic model.'), ('2. Interfaces', 'Inputs: GPS, IMU, EPS.')]}
            t['fmea'] = {'title': 'FMEA Report', 'sections': [('1. Methodology', 'RPN = S * O * D'), ('2. FMEA Matrix', make_md_table(self.fmea_table_headers[lang], self.fmea_table_data))]}
            t['valid'] = {'title': 'Validation Report', 'sections': [('1. Environment', 'MetaSpace Core v2.0 Sandbox'), ('2. Test Cases', 'TC-01..TC-04 Stress Test'), ('3. Results', make_md_table(self.validation_table_headers[lang], self.validation_table_data)), ('4. Verdict', 'SYSTEM ACCEPTED.')]}
        return t

# --- 2. RENDERER ---

def render_html(lang, meta, title, doc_id, sections):
    css = "body { font-family: 'Times New Roman', serif; max-width: 21cm; margin: 0 auto; padding: 20mm; } table { width: 100%; border-collapse: collapse; margin: 20px 0; } th, td { border: 1px solid #000; padding: 8px; text-align: left; } th { background-color: #f0f0f0; } .logo { color: #ccaa00; font-weight: bold; } .footer { margin-top: 50px; font-size: 0.8em; color: #666; border-top: 1px solid #ccc; }"
    
    html = f"<!DOCTYPE html><html lang='{lang}'><head><meta charset='UTF-8'><title>{title}</title><style>{css}</style></head><body>"
    html += f"<table style='width:100%; border:2px solid black; border-collapse:collapse; margin-bottom:20px;'><tr><td width='50%' style='border:1px solid black; padding:10px;'><span class='logo'>{meta['company']}</span><br>{meta['project']}</td><td width='25%' style='border:1px solid black; padding:10px;'><strong>{meta['doc_id_label']}:</strong><br>{doc_id}</td><td width='25%' style='border:1px solid black; padding:10px;'><strong>{meta['ver_label']}:</strong><br>1.0.5</td></tr><tr><td style='border:1px solid black; padding:10px;'><strong>{title}</strong></td><td style='border:1px solid black; padding:10px;'><strong>{meta['date_label']}:</strong><br>2026-01-10</td><td style='border:1px solid black; padding:10px;'><strong>{meta['sheet_label']}:</strong><br>1</td></tr></table>"
    html += f"<h1>{title}</h1>"
    
    for sec_title, content in sections:
        html += f"<h2>{sec_title}</h2>"
        if "|" in content and "---" in content:
            # Robust table parsing
            rows = content.strip().splitlines()
            html += "<table>"
            for i, row in enumerate(rows):
                if '---' in row: continue
                cols = [c.strip() for c in row.split('|') if c.strip()]
                tag = 'th' if i == 0 else 'td'
                html += "<tr>" + "".join([f"<{tag}>{c}</{tag}>" for c in cols]) + "</tr>"
            html += "</table>"
        else:
            html += f"<p>{content.replace('\n', '<br>')}</p>"
    html += f"<div class='footer'>{meta['footer']}<br>{meta['status']}</div></body></html>"
    return html

def render_md(meta, title, doc_id, sections):
    md = f"# {title}\n\n**{meta['project']}**\n* ID: {doc_id}\n* Author: {meta['company']}\n\n---\n\n"
    for st, ct in sections:
        md += f"## {st}\n\n{ct}\n\n"
    md += "---" + meta['footer']
    return md

def main():
    dp = ContentData()
    if not os.path.exists("certification_package"): os.makedirs("certification_package")
    for lang in ['en', 'hu', 'ro']:
        lp = os.path.join("certification_package", lang.upper())
        if not os.path.exists(lp): os.makedirs(lp)
        data = dp.get_content(lang)
        meta = data['meta']
        for fn, dd in [('01_Safety_Case', data['safety']), ('02_System_Spec', data['spec']), ('03_FMEA', data['fmea']), ('04_Validation_Report', data['valid'])]:
            doc_id = f"{fn}-{lang.upper()}-{dp.doc_id_base}"
            with open(os.path.join(lp, f"{fn}.html"), 'w', encoding='utf-8') as f:
                f.write(render_html(lang, meta, dd['title'], doc_id, dd['sections']))
            with open(os.path.join(lp, f"{fn}.md"), 'w', encoding='utf-8') as f:
                f.write(render_md(meta, dd['title'], doc_id, dd['sections']))
    print("Final Documents Generated Successfully.")

if __name__ == "__main__":
    main()
